### ISSUE TITLE
Trouble getting discord bot (python) to run on heroku

### ISSUE THREAD

**Issue by sunnywing** [sunnywing/vigilant-potato#1]
I have no issues running the bot directly from my computer, but when I try to run it using Heroku I get a "command not found" error from the Heroku log. I suspect it could be a missing package in requirements.txt but not sure how to check (if that is the issue).

I am still fairly new to programming and thought this project would be a good learning experience. Any help would be greatly appreciated.

project is under #vigilant-potato
[heroku-log.txt](https://github.com/sunnywing/vigilant-potato/files/2376461/heroku-log.txt)

**Comment by hakuli** [comment]
Hey there.

Still fairly new to Heroku myself, but I think your problem is the procfile.

I think you need to change the command that the worker dyno invokes to `python bot.py`, so that your procfile looks like:

`worker: python bot.py`

**Comment by sunnywing** [comment]
Yes you were right! I had to make a few minor changes with the bot.py code (to keep token hidden) and now it is successfully up and running on Heroku.

Thanks for the guidance.
